### ISSUE TITLE
[Bug] Incorrect cursor positioning on click at end of line

### ISSUE THREAD

**Issue by angelorodem** [firejump/vscode-frame-rainbow#1]
There is a bug that when a user clicks on a line close to the end it will not position the cursor at the end of the line, but one char before.

**Comment by firejump** [comment]
@angelorodem Thank you for the bug report.
This is really interesting; I'm able to reproduce this, though this happens on a minority of lines on the files I tested. The bug consistently reproduces on these lines and consistently doesn't on others. 
It appears that the distinguishing attribute of the lines with buggy cursor behaviour is their length; on the file I'm looking at right now the threshold is 26 characters - every line with that length or less will reproduce the bug. However, this threshold is dependent on the length of the longest line in the file, if that changes the threshold does too, and I don't yet see a clear relationship between the two.
I had a hunch this could be related to the tabnine/copilot compatibility mode introduced in https://github.com/firejump/vscode-frame-rainbow/commit/f0b41a913ff8c94c2a106884423a4a574eebe28c, and the bug indeed disappears when I revert that commit - but that's not really a solution. I'll keep digging and update once I get some results.

**Comment by firejump** [comment]
OK, I believe this is fixed in https://github.com/firejump/vscode-frame-rainbow/commit/e6e89e6d91992b1e3e405ccfed38101b3291e29c .
I've released the fix as pre-release version 0.1.2 .
@angelorodem Would you mind installing that version and letting me know if it works for you, and if you noticed any other adverse effects? See https://code.visualstudio.com/updates/v1_63#_pre-release-extensions if you haven't installed pre-release extension versions before.

**Comment by michael3557** [comment]
Thank you for the fix. I have installed the pre-release version 0.1.2 and it has completely fixed this issue for me. 

As a side note for me it included selections, and only seemed to effect html not CSS. the only two I am currently working on.
I was unable to select the last character of any line with the mouse, I had to use the curser.

**Comment by cmorman89** [comment]
Fixed for me, too. I was going crazy trying to figure out what extension was causing it.

**Comment by markur4** [comment]
Sadly, I am experiencing this bug right now. Disabling frame-rainbow fixed it and re-enabling frame-rainbow introduces the bug again.

**Comment by firejump** [comment]
I've released the fix ( https://github.com/firejump/vscode-frame-rainbow/commit/e6e89e6d91992b1e3e405ccfed38101b3291e29c )  in version 0.1.3. Closing.
